### ISSUE TITLE
Binary downloads fail 

### ISSUE THREAD

**Issue by mattyg** [lightningrodlabs/electron-holochain#13]
Running `npm run try-binary-download` fails consistently with an ECONNRESET after downloading 24.94mb of a 26.6mb file.

I tried swapping out the `request` library for node 18's built in fetch, the built-in `https`, and  some other 3rd party http request libraries (`needle`, `node-fetch-commonjs`). I still couldn't figure out how to resolve this issue. Hoping you have some ideas.

I'm on node 18.12.0 on linux.

**Comment by mattyg** [comment]
upgrading to node 20.5.1 resolved it

**Comment by Connoropolous** [comment]
hey @mattyg 
I'd love to know what you're using electron-holochain for?

**Comment by mattyg** [comment]
Hey Connor, I want to create a version of holochain-kangaroo for electron to publish a mewsfeed build with. 

Unfortunately I'm still having the issue on node 20. Except now the download doesn't fail, so the tar extraction runs, but the resulting binaries are corrupted (nowhere near their expected size).

**Comment by Connoropolous** [comment]
did you know about this?
https://github.com/lightningrodlabs/electron-holochain-template

**Comment by Connoropolous** [comment]
it does need updating though

**Comment by mattyg** [comment]
Yeah I'll probably copy a bunch from it, thanks. 

I'll close this issue again I need to debug it more.
